default_stages: [pre-commit, pre-merge-commit, pre-push, manual]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2 # Ruff version
    hooks:
      # Run the linter.
      # Needs to placed before black, isort, and other formatters
      - id: ruff
        args: [--fix]
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
      - id: end-of-file-fixer
        name: fix end of files
        entry: end-of-file-fixer
        language: python
        types: [text]
      - id: check-added-large-files
        name: check for added large files
        entry: check-added-large-files
        language: python
        types: [text]
      - id: check-license-header
        name: check for correct license header
        entry: licenseheaders
        args: ["-t", "license_header.tmpl", "--files"]
        language: python
        types: ["python"]
        pass_filenames: true
      - id: docformatter
        name: docformatter
        entry: docformatter
        args: [--in-place]
        language: python
        types: ["python"]
      - id: commitizen
        name: commitizen
        entry: cz
        args: ["check", "--commit-msg-file", ".git/COMMIT_EDITMSG"]
        pass_filenames: false
        language: system
        stages: [commit-msg, manual]
      - id: isort
        name: isort (python)
        entry: isort
        language: python
        always_run: false
        pass_filenames: true
        additional_dependencies: ["toml"]
      - id: black
        name: black
        entry: black
        language: python
        types: ["python"]
        always_run: false
        pass_filenames: true
        additional_dependencies: ["toml"]
      - id: yamllint
        name: yamllint
        entry: yamllint
        args:
          - > # This is needed to lint the jinja templates
            -d={extends: default, rules: {braces: {max-spaces-inside: 1}
            , brackets: disable, document-start: disable, "line-length": {"max": 100}}}
          - -f=colored
        language: python
        types: ["yaml"]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
        always_run: false
        pass_filenames: true
        exclude: '^tests/integration_tests/'
      - id: pylint-integration-tests
        name: pylint (tests)
        entry: pylint --disable=duplicate-code
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
        always_run: false
        pass_filenames: true
        files: '^tests/integration_tests/'
      - id: mypy
        name: mypy (check type hinting)
        entry: mypy
        language: python
        types: ["python"]
        pass_filenames: true
        # Delete modules once type hinting has been introduced there
        exclude: |
          (?x)(
          ^(.gitlab|.github|config|doc|tests|test_utils)/|
          ^src/(example_simulator_functions|queens_interfaces)/|
          ^src/queens/(data_processors|drivers|iterators|models|parameters)/|
          ^src/queens/(schedulers|stochastic_optimizers|variational_distributions|visualization)/|
          ^src/queens/(main.py|global_settings.py)
          ).*$
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: Strip outputs from Jupyter notebooks
        files: \.ipynb$
